mixed = (1,2,3,4.0)
nums =(1,)
words = ('word1',)
guitars = 'yamaha', 'baton rouge', 'taylor'
guitarists = ('Maneli Jamal','Eddie Van Der Meer','Andrew Foy')
guitarist1,guitarist2,guitarist3 = (guitarists)
favourites = ('southern mangolia',['Tokyo Ghoul Theme','landscape'])
favourites[1].pop()
favourites[1].append('we made it')
print(favourites)
print(sum(mixed))